// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB63YyZfWJsmKqJBh6p3WgMxVaa74l0dMU',
    appId: '1:80203879065:web:bd446fa0733ad278651e08',
    messagingSenderId: '80203879065',
    projectId: 'longin-8f384',
    authDomain: 'longin-8f384.firebaseapp.com',
    storageBucket: 'longin-8f384.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLeJ0aKRkKRZKCl16s-A8mdu2SmhT3yKI',
    appId: '1:80203879065:android:577a5745cc9e4bf0651e08',
    messagingSenderId: '80203879065',
    projectId: 'longin-8f384',
    storageBucket: 'longin-8f384.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA43fs8kbWQmuR1acvZW3DKYJPyIrADyWs',
    appId: '1:80203879065:ios:c091db41e5213e5f651e08',
    messagingSenderId: '80203879065',
    projectId: 'longin-8f384',
    storageBucket: 'longin-8f384.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA43fs8kbWQmuR1acvZW3DKYJPyIrADyWs',
    appId: '1:80203879065:ios:c091db41e5213e5f651e08',
    messagingSenderId: '80203879065',
    projectId: 'longin-8f384',
    storageBucket: 'longin-8f384.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB63YyZfWJsmKqJBh6p3WgMxVaa74l0dMU',
    appId: '1:80203879065:web:e6fd8864c0c496e5651e08',
    messagingSenderId: '80203879065',
    projectId: 'longin-8f384',
    authDomain: 'longin-8f384.firebaseapp.com',
    storageBucket: 'longin-8f384.appspot.com',
  );
}
